# Generated by Django 3.0.6 on 2020-05-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('calificacion', models.IntegerField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
