# Generated by Django 3.0.6 on 2020-05-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETA_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Alumno',
        ),
    ]
