# Generated by Django 3.0.6 on 2020-05-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETA_App', '0002_auto_20200528_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
