# Generated by Django 3.0.6 on 2020-05-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETA_App', '0005_auto_20200530_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='email',
        ),
    ]
