# Generated by Django 3.0.6 on 2020-05-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETA_App', '0006_auto_20200530_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='string',
            new_name='password',
        ),
    ]
